name: Frontend App

env:
  APP_NAME: backend-app
  IMAGE_TAG: "dev-${{github.run_number}}"

on:
  push:
    branches:
      - main
      - dev
      - feature-*
  workflow_dispatch:
    
jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Checkout app-configs repository
        uses: actions/checkout@v2
        with:
          repository: argo-universe/app-configs
          ref: main
          token: ${{ secrets.GIT_PAT }}
          path: app-configs

      - name: Run build script
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          IMAGE_NAME: ${{ env.APP_NAME }}
        run: | 
          chmod +x app-configs/scripts/build.sh
          app-configs/scripts/build.sh
      - name: Install Trivy
        run: |
          TRIVY_LATEST_RELEASE=$(curl -s https://api.github.com/repos/aquasecurity/trivy/releases/latest | grep "browser_download_url.*_Linux-64bit.deb" | cut -d '"' -f 4 | head -n 1)
          wget "$TRIVY_LATEST_RELEASE" -O trivy.deb
          sudo dpkg -i trivy.deb

      - name: Scan Docker image for vulnerabilities
        run: |
          IMAGE_TAG="argouniverse/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}"
          trivy image --exit-code 1 --no-progress $IMAGE_TAG || true
          
      - name: Run image tag script
        env: 
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          ENV: dev
          APP_NAME: ${{ env.APP_NAME }}
        run: | 
          chmod +x app-configs/scripts/update_imagetag.sh
          app-configs/scripts/update_imagetag.sh